IMP: Subsample action renamed to 'subsample_ids'
qiime2/q2-feature-table pull request #301
Opened 2023-12-22 22:12 UTC by hagenjp

Closes: [#299 ](https://github.com/qiime2/q2-feature-table/issues/299)

Include any questions for reviewers, screenshots, sample outputs, etc.

2023-12-22 23:25 UTC, lizgehret requested changes
Hey @hagenjp! This mostly looks good, but the tests are failing because you've replaced the name of an external method (`Table.subsample`) with `subsample_ids`, which doesn't exist. I'm going to let you find the instances of this and replace them with the original method, because I think it's a good exercise to recognize the difference between external methods that we're calling and our own internal methods (within QIIME 2). In your basecamp message, you already identified where that external method is being called from, so I'll let you extrapolate from there 🙂 

Let me know if you have any questions!

2024-01-03 17:13 UTC, hagenjp commented
@lizgehret this pr is ready for round two review from you :)

2024-01-04 20:40 UTC, lizgehret approved these changes
lgtm, just one small comment inline!

2024-01-04 20:40 UTC, lizgehret commented on q2_feature_table/tests/test_subsample.py
>  class SubsampleTests(TestCase):
```suggestion
class SubsampleIDsTests(TestCase):
```
I think you had the right idea when you changed the name of this class @hagenjp - it's consistent with the name changes you've implemented within all of the subsequent tests, so changing the class name as well makes sense to me!

2024-01-04 23:03 UTC, lizgehret commented
looks great, thanks @hagenjp!

2024-01-04 23:03 UTC, merged