ENH: Added "seed" parameter to `subsample-ids`
qiime2/q2-feature-table pull request #317
Opened 2024-10-23 09:46 UTC by VinzentRisch

closes #55 

- Adds seed parameter to `subsample-ids` function.
- Seed is per default set to 1. It can be set to "random" what creates a random 32 bit int as the seed. 
- Setting the seed to default 1 was done to ensure that the seed is logged in provenance. This improved reproducability.
- At this point it is not possible to have a random seed that is created in the function that will be recorded in provenance.

2024-12-16 17:53 UTC, gregcaporaso commented on q2_feature_table/_subsample_ids.py
> +                  axis: str, seed: Union[int, str] = 1) -> biom.Table:
```suggestion
                  axis: str, seed: Union[int, str] = "random") -> biom.Table:
```

2024-12-16 17:59 UTC, gregcaporaso requested changes
@VinzentRisch, I thought I left a comment on this earlier today, but I see to have lost it so I'm thinking maybe it didn't save and I navigated away from the page. But, apologies if this feedback is showing up twice. 

I completely agree that we need to be storing random seeds in provenance, but the approach implemented here will be problematic. The vast majority of users won't notice or override this parameter setting, in which case the result will be that the same seed is used all the time. 

We have support for passing random seeds on the command line in q2-boots - see how we handle this here:
https://github.com/caporaso-lab/q2-boots/commit/9195f9cfac1694196e1dfcc68934301d9238b350

Could you update this PR to use this approach? 

I created a framework issue to develop an approach for better supporting this:
https://github.com/qiime2/qiime2/issues/823

2024-12-16 18:01 UTC, gregcaporaso commented on q2_feature_table/_subsample_ids.py
> +    if seed == "random":
You can use the built-in [`random.seed` function](https://docs.python.org/3/library/random.html#random.seed) for this.

2024-12-16 18:07 UTC, gregcaporaso commented
Oh, I see - my previous comment was on #321. This feedback is relevant to both of the PRs.

2025-01-23 17:08 UTC, gregcaporaso requested changes
@VinzentRisch, could you update this PR to mirror the approaches we've taken to this functionality and the tests in #321?

2025-01-23 17:08 UTC, gregcaporaso commented on q2_feature_table/_subsample_ids.py
> +                  axis: str, seed: Union[int, str] = 1) -> biom.Table:
```suggestion
                  axis: str, seed: int = None) -> biom.Table:
```

2025-01-23 17:08 UTC, gregcaporaso commented on q2_feature_table/_subsample_ids.py
> +
This should all be able to go away since this happens in `Table.subsample` - right? 

```suggestion
```

2025-01-23 17:08 UTC, gregcaporaso commented on q2_feature_table/plugin_setup.py
> +                'seed': Int % Range(0, 2**32) | Str % Choices(["random"])
```suggestion
                'seed': Int % Range(0, None)
```
```suggestion
                'seed': Int % Range(0, 2**32) | Str % Choices(["random"])
```

2025-01-23 17:08 UTC, gregcaporaso commented on q2_feature_table/plugin_setup.py
> +                 'seed will not be logged in provenance.')
Edits to the text. I'd leave the bit about provenance out, since we'll ideally be fixing that very shortly and it's common to all actions that take seeds right now. 

```suggestion
        'seed': ('Set the seed for the subsampling. Using the same seed with '
                 'the same table will always lead to the same result. By '
                 'default a random seed will be used.')
```

2025-01-23 17:08 UTC, gregcaporaso commented on q2_feature_table/tests/test_subsample.py
> +        a = subsample_ids(t, 2, 'sample', 'random')
Can you adapt these tests to be similar to the ones we put together for #321?

2025-08-14 18:10 UTC, gregcaporaso commented
@VinzentRisch - is this still something you're interested in working on?

2025-08-19 08:09 UTC, VinzentRisch commented
Hey @gregcaporaso 
Sorry! this got lost on my todo list. I will take a look today.

2025-08-19 13:08 UTC, VinzentRisch commented
Hey @gregcaporaso 
Again sorry for the oversight. I added all the changes similar to https://github.com/qiime2/q2-feature-table/pull/321.

2025-10-16 21:22 UTC, gregcaporaso approved these changes
@VinzentRisch, this looks good, thank you! I made a fix (and a simplification) to the tests. The tests were all right, but the message that would have been printed on failure (regarding the use or non-use of a random seed) was backwards such that a confusing message would have been printed on failure. 

This is ready for merge once the tests pass.

2025-10-16 21:33 UTC, merged